services:
  database:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: api/v1
      target: production-stage
    depends_on:
      - api
    # For local testing add a concrete port mapping here, e.g. "8000:80"
    ports:
      - "80:80"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: production-stage
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - DB_URL=jdbc:mariadb://database:3306/pe2?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  database_data:
